### ISSUE TITLE
Sync at 100.1%

### ISSUE THREAD

**Issue by SatoNaka55** [Greg-Griffith/Lynx#1]
Sometimes goes up to 103% when syncing.
![walletbug](https://user-images.githubusercontent.com/35282281/34753420-d6a008f8-f585-11e7-8d32-d58d960b4c6f.png)

**Comment by Greg-Griffith** [comment]
this issue has been fixed in #266a9a618cfe571c012564fa80e9612501fedb27 and will be reflected in the next full version release
