### ISSUE TITLE
Error: Address already exist

### ISSUE THREAD

**Issue by mammalammam** [Greg-Griffith/Lynx#12]
On the "Send" tab, when trying to add an address it displays "Error: Address already exist".

![lynx_2017-10-12_16-55-42](https://user-images.githubusercontent.com/32727286/31483097-5cc899da-af6e-11e7-8013-ecd087c772c9.png)

**Comment by Greg-Griffith** [comment]
fixed in commit 5fb33bec98d3413e9747cb6af9c02b187e0f7fcd
